myvalentine/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.http import HttpResponse

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myvalentine.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('valentine.urls', namespace="valentine")),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls',namespace='social')),
    url('', include('django.contrib.auth.urls',namespace='auth')),
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    (r'^robots.txt$',lambda r: HttpResponse("User-agent: *\nDisallow:", mimetype="text/plain")),
     
)

valentine/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from valentine import views
from django.http import HttpResponse
admin.autodiscover()

urlpatterns = patterns('',
	url(r'^$',views.index, name ='index'),
	url(r'^middle/$',views.middle,name='middle'),	
	url(r'^register/$',views.register, name ='register'),
	url(r'^logout/$',views.logout, name ='logout'),
	url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
	#(r'^robots\.txt$',lambda r: HttpResponse("User-agent: *\nDisallow:", mimetype="text/plain")),
)

valentine/models.py
from django.db import models
from django.utils import timezone
import datetime

class UserEntry(models.Model):
	match_email=models.EmailField(max_length=100,blank=True,null=True)
	user_fullname=models.CharField(max_length=100)
	user_email=models.EmailField(max_length=100,unique=True)
	user_pic = models.ImageField(blank = True, null = True)
	#user_altemail=models.EmailField(max_length=100,default=0000)
	date_of_selection=models.DateTimeField('date of selction',blank=True,null=True)
	date_of_match=models.DateTimeField('date of match',blank=True,null=True)
	#place=models.CharField(max_length=20,blank=True,null=True)
	ip_address=models.GenericIPAddressField()
	gender = models.CharField(max_length= 10) #False = Male
	friends_count=models.IntegerField(max_length=5,blank=True,null=True)
class EntryChoice(models.Model):
	choice = models.ForeignKey(UserEntry)
	choice_names=models.CharField(max_length=100)
	choice_email=models.EmailField(max_length=100)
	choice_altemail=models.EmailField(max_length=100)

valentine/views.py
from django.shortcuts import render, get_object_or_404, render_to_response 
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import auth
from django.core.context_processors import csrf
from valentine.models import UserEntry,EntryChoice
from django.utils import timezone
import datetime
import urllib2
from django.core.urlresolvers import reverse
from django.core.mail import send_mail, BadHeaderError
from django.template.context import RequestContext
from ipware.ip import get_ip
import ipdb
from facepy import GraphAPI
from django_facebook.decorators import facebook_required
from facepy.exceptions import OAuthError
#from facepy.utils import get_extended_access_token
from social_auth.models import UserSocialAuth


def index(request):
		context = RequestContext(request,{'request': request,'user': request.user})
		return render_to_response('valentine/index.html',context_instance=context)

def middle(request):
	try:
		instance = UserSocialAuth.objects.filter(provider='facebook').get(id = request.user.id-1)
		graph = GraphAPI(instance.extra_data['access_token'])
		#graph.post(
				#path = 'me/feed',
				#message = 'use this awesome app valentine',
				#link='http://valentine.com:8000'
				#) 
		profile_pic=graph.get(
				path = 'me/picture?fields = url&redirect=false&height=150&width=150',
				) 
		context = RequestContext(request,{'request': request,'user': request.user, 'profile_pic':profile_pic})
		return render_to_response('valentine/sub1.html',context_instance = context)
	except:
		return HttpResponseRedirect('/')

def register(request):
		if request.method=="POST":
			instance = UserSocialAuth.objects.filter(provider='facebook').get(id = request.user.id-1)
			#short_lived_access_token = 'CAAMkkm5SZCZBcBAE4Rh0ZAhBTetqpxXp6HgRT1ZBcwZCjvvVBgJEHvVWNAZCDLepm92NkyTHcBqlnQuS1RYILzXMvGeVr9haZAy8z5U5xuxJZAklF58dfY5r43ZCIZBMR10xbKoXJiqMpRNMRI1ZCDCX7WD6NDFH1ISChae4JA3AZAUZC9uhxRAQ8aAx1koeaSv27h2Wn90ZAfhZCX3yhjETIs0lNwE'
			#application_id='884636264890343'
			#application_secret_key='76ea9acba9eec25eb8d78ddc57dc1cf3'
			#long_lived_access_token, expires_at = get_extended_access_token(short_lived_access_token, application_id, application_secret_key)
			graph = GraphAPI(instance.extra_data['access_token'])
			
			profile_pic=graph.get(
				path = 'me/picture?fields = url&redirect=false&height=150&width=150',
				) 
			gender = graph.get(
				path = 'me?fields= gender'
				)
			friends=graph.get(
				path='me/friends?fields=friends'
				)
			ip = get_ip(request)
			fbid0=request.user.username
			mailid0=request.POST.get('mailid0',None)
			if mailid0 is None:
				mailid0=request.user.email
			#gender= request.user.gender
			#mailid10=request.POST.get('mailid10',None)
			#place=request.POST.get('place','')
			date_selection=timezone.now()
			try:
				obj_Userentry=UserEntry(user_fullname=fbid0,user_email=mailid0,date_of_selection=date_selection,ip_address=ip)
				obj_Userentry.save()
			except:
				return render_to_response('valentine/error.html',{'user': request.user, 'profile_pic':profile_pic})
			i=1
			namess=[]
			mailids=[]
			altmailids=[]
			while i<6:
				
				names=request.POST.get('name'+str(i),None)				
				mail = request.POST.get('mailid'+str(i),None)
				altmail = request.POST.get('mailid1'+str(i),None)
				obj_Entrychoice=EntryChoice(choice=obj_Userentry)
				if names is not None:
					namess.append(names)
					obj_Entrychoice.choice_names=names
				
				if mail is not None:
					mailids.append(mail)
					obj_Entrychoice.choice_email=mail

				if altmail is not None:
					altmailids.append(altmail)
					obj_Entrychoice.choice_altemail=altmail
				obj_Entrychoice.save()
				i=i+1
			instance = UserSocialAuth.objects.filter(provider='facebook').get(id = request.user.id-1)
			#short_lived_access_token = 'CAAMkkm5SZCZBcBAE4Rh0ZAhBTetqpxXp6HgRT1ZBcwZCjvvVBgJEHvVWNAZCDLepm92NkyTHcBqlnQuS1RYILzXMvGeVr9haZAy8z5U5xuxJZAklF58dfY5r43ZCIZBMR10xbKoXJiqMpRNMRI1ZCDCX7WD6NDFH1ISChae4JA3AZAUZC9uhxRAQ8aAx1koeaSv27h2Wn90ZAfhZCX3yhjETIs0lNwE'
			#application_id='884636264890343'
			#application_secret_key='76ea9acba9eec25eb8d78ddc57dc1cf3'
			#long_lived_access_token, expires_at = get_extended_access_token(short_lived_access_token, application_id, application_secret_key)
			graph = GraphAPI(instance.extra_data['access_token'])
			
			profile_pic=graph.get(
				path = 'me/picture?fields = url&redirect=false&width=150&height=150',
				) 
			gender = graph.get(
				path = 'me?fields= gender'
				)
			friends=graph.get(
				path='me/friends?fields=friends'
				)
			profile_picc=profile_pic['data']
			#obj_Userentry.user_pic = profile_picc['url']
			#friends_countt=friends['summary']
			#obj_Userentry.friends_count=friends_countt['total_count']
			obj_Userentry.gender = gender['gender']
			obj_Userentry.save() 
			#send_mail(subject,flag,'sampleimaginate@gmail.com',[mailid0,mailid10])	
			trymail='Heyyy...!! Here is an awesome way to express your feelings on your secret crush without disclosing your identity. Some of your friends made a try and conveyed their crush on you. You are just a click away ( http://coffeehangout.com) from finding your secret crush... '	
			matchflag='It seems like your crush is yet to convey her feelings. We have sent her a mail anonymously. Just stay calm and keep Loving your Crush...!! We will notify you when your crush responds'
			subject='valentine app results'
			for mail in mailids:
				if mail is not None:
					try:
						send_mail(subject,trymail,'cupid@coffeehangout.com',[mail])
					except:
						mail=None

			for mail in altmailids:
				if mail is not None:
					try:
						send_mail(subject,trymail,'cupid@coffeehangout.com',[mail])
					except:
						mail=None
			if UserEntry.objects.all()>1:
				for i in range(0,5):
					#choice_fb_obj = UserEntry.objects.filter(user_fb = fbids[i],match_email=None)
					choice_email_obj = UserEntry.objects.filter(user_email = mailids[i],match_email=None)
					#choice_emailaltemail_obj = UserEntry.objects.filter(user_altemail = mailids[i],match_email=None,friends_count__gt=40)
					choice_altemailemail_obj = UserEntry.objects.filter(user_email = altmailids[i],match_email=None)
						#choice_altemail_obj = UserEntry.objects.filter(user_altemail = altmailids[i],match_email=None,friends_count__gt=40)
					#choicesfb = EntryChoice.objects.all().filter(choice = choice_fb_obj)
					choicesemail = EntryChoice.objects.all().filter(choice = choice_email_obj)
					#choicesemailaltemail = EntryChoice.objects.all().filter(choice = choice_emailaltemail_obj)
					choicesaltemailemail = EntryChoice.objects.all().filter(choice = choice_altemailemail_obj)
					#choicesaltemail = EntryChoice.objects.all().filter(choice = choice_altemail_obj)
					flag = 'unmatch'
						
					if flag =='unmatch':
						for matchemail in choicesemail:
							if matchemail.choice_email==mailid0:
								flag='match'
								obj_Userentry.match_email=mailids[i]
								obj_Userentry.save()
								obj_Userentry.date_of_match=timezone.now()
								obj_Userentry.save()
								choice_email_match = UserEntry.objects.get(user_email = mailids[i])
								choice_email_match.match_email=mailid0
								choice_email_match.date_of_match=timezone.now()
								choice_email_match.save()
								matchflag= 'Congrats...!! Your crush already expressed feelings on you and waiting for you... Go and have a lovely hangout with your crush,%s @ %s'%(namess[i],mailids[i])
								matchflag1='Yippie..!! And now the wait is over... Your crush, %s responded on having a secret crush on you. Go and have a lovely hangout with your crush, @ %s'%(fbid0,mailid0)
								send_mail(subject,matchflag1,'cupid@coffeehangout.com',[mailids[i]])
								break
							
							elif matchemail.choice_altemail==mailid0:
								flag='match'
								obj_Userentry.match_email=mailids[i]
								obj_Userentry.save()
								obj_Userentry.date_of_match=timezone.now()
								obj_Userentry.save()
								choice_email_match = UserEntry.objects.get(user_email = mailids[i])
								choice_email_match.match_email=mailid0
								choice_email_match.date_of_match=timezone.now()
								choice_email_match.save()
								matchflag='Congrats...!! Your crush already expressed feelings on you and waiting for you... Go and have a lovely hangout with your crush,%s @ %s'%(namess[i],mailids[i])

								matchflag1='Yippie..!! And now the wait is over... Your crush, %s responded on having a secret crush on you. Go and have a lovely hangout with your crush, @ %s'%(fbid0,mailid0)
								send_mail(subject,matchflag1,'cupid@coffeehangoutcom',[mailids[i]])
								break

								

						

					if flag =='unmatch':
						for matchemail in choicesaltemailemail:
							if matchemail.choice_email==mailid0:
								flag='match'
								obj_Userentry.match_email=altmailids[i]
								obj_Userentry.save()
								obj_Userentry.date_of_match=timezone.now()
								obj_Userentry.save()
								choice_email_match = UserEntry.objects.get(user_email = altmailids[i])
								choice_email_match.match_email=mailid0
								choice_email_match.date_of_match=timezone.now()
								choice_email_match.save()
								matchflag='Congrats...!! Your crush already expressed feelings on you and waiting for you... Go and have a lovely hangout with your crush,%s @ %s'%(namess[i],altmailids[i])

								matchflag1='Yippie..!! And now the wait is over... Your crush, %s responded on having a secret crush on you. Go and have a lovely hangout with your crush, @ %s'%(fbid0,mailid0)
								send_mail(subject,matchflag1,'cupid@coffeehangout.com',[altmailids[i]])
								break
							elif matchemail.choice_altemail==mailid0:
								flag='match'
								obj_Userentry.match_email=altmailids[i]
								obj_Userentry.save()
								obj_Userentry.date_of_match=timezone.now()
								obj_Userentry.save()
								choice_email_match = UserEntry.objects.get(user_email = altmailids[i])
								choice_email_match.match_email=mailid0

valentine/templates/valentine/error.html
{% load staticfiles %}
{% block main %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CoffeHangout with your valentine</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'valentine/css/bootstrap.min.css' %}" rel="stylesheet">
    <!--ladda-->
    <link rel="stylesheet" href="{% static 'valentine/dist/ladda.min.css' %}">  
    <script src="{% static 'valentine/dist/spin.js' %}"></script>
        <script src="{% static 'valentine/dist/ladda.js' %}"></script>


    <!-- Custom CSS -->
    <link href="{% static 'valentine/css/grayscale.css' %}" rel="stylesheet">
    <link href="{% static 'valentine/css/facebook_button.css' %}" rel="stylesheet">
   

    <!-- Custom Fonts -->
    <link href="{% static 'valentine/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59748878-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body id="page-top" data-spy="scroll" style="ba">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=884636264890343&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=884636264890343&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class="intro" id="middle_page">
        <div class="intro-body" >
            <div class="container">
                <form action="#" method="post" class="form" role="form" name="userform" id="userform">
                    <div class="row">
                        <div class="col-md-4 col-lg-4">
                            <img src="{{profile_pic.data.url}}" height="150" width="150" />
                        </div>
                        
                        <div class="col-md-4 col-lg-4 ">
                            <div class="row">
                                <div class="col-lg-12 col-md-12 ">
                                    <h3 ><span class="label label-primary">Your details</span></h3>
                                    <input class="form-control" name="fbid0" id="fbid0" placeholder="Facebook username" type="text" disabled value='{{ user.get_full_name|default:user.username }}' required /><br>
                                    <input class="form-control" name="mailid0" id="mailid0" placeholder="Your mail-id" type="email" value="{{ user.email }}" disabled autofocus/>
                                </div>        
                            </div>
                        </div>

			 <div class="col-md-4 col-lg-4 ">
                            <p><br><BR>
                               <a  href="{% url 'valentine:logout' %}" class="btn btn-social">
                                  <i class="fa fa-sign-out"></i> Logout
                                </a><br>
                            </p>




 	                       </div>
                      
                        
                    </div>
                <hr>
                    <div class="row">               
                        
<!--spinner begin-->    <div class="col-sm-12 col-md-12 col-lg-12">
                            <h1>You have already conveyed your feelings</h1>
			
			<p>Increase your chances of getting matched by sharing</p>
			     <div class="fb-share-button" data-href="http://coffeehangout.com" data-layout="button_count"></div><br>
<br><br>
<div class="fb-like-box" data-href="https://www.facebook.com/coffeehangout.valentine" data-colorscheme="dark" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true"></div>

                        </div>

                        <div class="col-sm-12 col-md-12 col-lg-12 spinner_place" >
                            <div class="row"> 
                                <div class="col-xs-12 col-md-12 col-lg-12">
                                    <img src="img/heart1.gif" alt="Loading.."/>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xs-12 col-md-12 col-lg-12">
                                    <p>
                                        Please wait..<br>
                                        We are searching matches by the email(s) provided by you.<br>
                                    </p>
                                </div>
                            </div>
<!--spinner close-->    </div>


<!--submit button -->                        
                        

                        
                    </div>            
                </form>

            </div> <!-- end of container-->
        </div>
    </div> 


    <!-- Footer >
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Imaginate 2015</p>
        </div>
    </footer -->


    
    <script>
        
       //var l = Ladda.create( document.querySelector( 'button' ) );
       //l.start();
       //l.stop();
       //l.toggle();
       //l.isLoading();
       //progress = Math.min( progress + Math.random() * 0.1, 1 );
       //l.setProgress( 0.5 );
    </script >

       




    <!-- jQuery -->
    <script src="{% static 'valentine/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'valentine/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'valentine/js/jquery.easing.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'valentine/js/grayscale.js' %}"></script>

</body>

</html>
{% endblock %}

valentine/templates/valentine/index.html
{% load staticfiles %}
{% block main %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta property="og:title" content="Coffee Hangout with your Crush" />
<meta property="og:description" content="Heyy..! Why to waste this Valentines Day sitting alone @ home. Have a secret crush..? Worried about expressing your feelings..? No worries...!! We are here to express your feelings anonymously" />
<meta property="og:url" content="http://coffeehangout.com" />
<meta property="og:image" content="{% static 'valentine/img/cover_pic.png'%}" />	
<meta name="google-site-verification" content="Zj7b3VZbXTgYLC0eMTBLsBuTUXLRtwwFfH5noIPZZ9U" />
    <title>Hangout with your Secret Crush</title>
    <link rel="shortcut icon" href="{% static 'valentine/img/hrt.ico' %}">

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'valentine/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'valentine/css/grayscale.css' %}" rel="stylesheet">
    <link href="{% static 'valentine/css/facebook_button.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'valentine/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style type="text/css">
      body {
             overflow-x:hidden;
           }
    </style>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59748878-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Intro Header -->
    <header class="intro" id="head">
        <div class="intro-body">
            <div class="container" id="main_container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">Valentine</h1>
                        <p class="intro-text">Simple and secure way leading to a hangout with your crush for this Valentine's Day or any other Day.</p>
                        <div id="self_btn">
                        <a href="#head" class="btn btn-circle page-scroll up">
                            <i class="fa fa-angle-double-down animated"></i>
                        </a>
                        <a href="#services" class="btn btn-circle page-scroll down">
                            <i class="fa fa-angle-double-up animated"></i>
                        </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!--features-->

    
    <!-- About Section -->

    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services bg-default">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <br><br>
                    <h2>Features</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-heart fa-stack-1x text-primary"></i>
                            </span>
                                <h4><br>
                                    <strong>Express</strong>
                                </h4>
                                <p>Express your feelings to your crush anonymously.</p>
                                
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-envelope fa-stack-1x text-primary"></i>
                            </span>
                                <h4><br>
                                    <strong>Notifications</strong>
                                </h4>
                                <p>Receive your match results with your crush through emails.</p>
                                
                            </div>
                        </div>
                        
                        
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-lock fa-stack-1x text-primary"></i>
                                </span>
                                <h4><br>
                                    <strong>Match</strong>
                                </h4>
                                <p>Your identity won't be revealed unless a match happens.</p>
                                
                            </div>
                        </div>

                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="fa-stack fa-4x">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x text-primary"></i>
                            </span>
                                <h4><br>
                                    <strong>Facebook</strong>
                                </h4>
                                <p>Share this application to make sure that your crush will reach us.</p>
                                
                            </div>
                        </div>

                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
 
            <div class="row text-center">
                <div class="col-lg-8 col-lg-offset-2">
                       <br><br><br><br><br><br>
                        <p>
                           <a  href="{% url 'social:begin' 'facebook' %}?next={%url 'valentine:middle' %}" class="btn btn-social btn-facebook">
                              <i class="fa fa-facebook"></i> Sign in with Facebook
                            </a><br>
			<small style="font-size:10px;">CoffeeHangout doesn't post on your timeline without your permission</small>
                        </p>        			
			<br>
                </div>
            </div>
        </section>

        








    
    <!-- Footer >
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Imaginate 2015</p>
        </div>
    </footer -->

    <!-- jQuery -->
    <script src="{% static 'valentine/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'valentine/js/bootstrap.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'valentine/js/jquery.easing.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script src="{% static 'valentine/js/grayscale.js' %}"></script>

</body>

</html>
 {% endblock %}